# -*- coding: utf-8 -*-
"""ml_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ub8Kep9MLq1f_ozs---T8wPA00I6fnMM

# Machine Learning with Django
## Build A Simple Machine Learning Web Application with Django | Part 1
  - [Youtube link](https://youtu.be/sTjL51Gr1wE?list=PLInvlTu9nmo8ngRePTSPuqQdeLAGe0-Is)

### Import Libraries
"""

import pandas as pd

"""### Import data"""

data = pd.read_csv('sport_data.csv')

"""### Basic Data Analysis"""

data

data.head()

data.tail()

data.shape

data.describe()

"""### Pre-Processed Data"""

data['Sex'].replace(['Female', 'Male'], [0, 1], inplace=True)

data.head()

data.tail()

"""### Import Machine Learning Libraries"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

X = data.drop(columns='Sport')

X.head()

y = data.drop(columns=['Age', 'Height', 'Sex'])

y.head()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

"""### Build Machine Learning Model"""

clf = DecisionTreeClassifier()

clf.fit(X_train, y_train)

"""### Test ML Model"""

test = clf.predict(X_test)

test

y_test

"""### Check for Efficacy"""

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test, test)

accuracy

new_student = clf.predict([[15, 4, 1]])

new_student

"""### Save Model"""

# from sklearn.externals import joblib
import joblib

joblib.dump(clf, 'ml_sport_model.joblib')

import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

c_matrix = confusion_matrix(y_test, test)
c_matrix

cm = confusion_matrix(y_test, test, labels=clf.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=clf.classes_)
disp.plot()
plt.show()

y_test

"""### Check the accuracy in depth"""

print(classification_report(y_test, test))

# precision    recall  f1-score   support

#   Basketball       1.00      0.67      0.80         3
#       Hockey       1.00      1.00      1.00         2
#       Soccer       0.50      1.00      0.67         1

#     accuracy                           0.83         6
#    macro avg       0.83      0.89      0.82         6
# weighted avg       0.92      0.83      0.84         6