# -*- coding: utf-8 -*-
"""run_ml_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NZfHs5U_vRDAOdoDU53ma0ol4uuDQ2KO
"""

from sklearn.tree import DecisionTreeClassifier
import joblib

model = joblib.load('ml_sport_model.joblib')

new_student2 = model.predict([[15, 4, 1]])

new_student2

